return {
  {
    'nvim-treesitter/nvim-treesitter',
    config = function(opts)
      local parser_configs = require 'nvim-treesitter.parsers'
      local parser_config = parser_configs.get_parser_configs()
      parser_config.commonlisp = {
        install_info = {
          url = '~/projects/javascript/new-tree-sitter-cl/',
          files = { 'src/parser.c' },
          generate_requires_npm = false,
        },
      }
      require('lspconfig.ui.windows').default_options.border = 'single'
      return require('nvim-treesitter.configs').setup(opts.opts)
    end,
    opts = {
      auto_install = true,
      ensure_installed = {
        'lua',
        'luap',
        'luadoc',
        'vim',
        'vimdoc',
        'fennel',
        'requirements',
        'python',
        'pymanifest',
        'bash',
        'awk',
        'readline',
        'json',
        'json5',
        'jsonc',
        'jq',
        'yaml',
        'xml',
        'toml',
        'sql',
        'tsv',
        'org',
        'markdown',
        'markdown_inline',
        'mermaid',
        'rst',
        'http',
        'html',
        'javascript',
        'typescript',
        'css',
        'jsdoc',
        'tsx',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'git_config',
        'git_rebase',
        'diff',
        'printf',
        'regex',
        'dockerfile',
        'llvm',
        'asm',
        'disassembly',
        'ini',
      },
      -- textobjects = {
      --   move = {
      --     enable = true,
      --     set_jumps = true,
      --     goto_next_end = { [']M'] = '@function.outer', [']['] = '@class.outer' },
      --     goto_next_start = { [']]'] = '@class.outer', [']m'] = '@function.outer' },
      --     goto_previous_end = { ['[M'] = '@function.outer', ['[]'] = '@class.outer' },
      --     goto_previous_start = { ['[['] = '@class.outer', ['[m'] = '@function.outer' },
      --   },
      --   select = {
      --     enable = true,
      --     lookahead = true,
      --     keymaps = {
      --       aa = '@parameter.outer',
      --       ac = '@class.outer',
      --       af = '@function.outer',
      --       ia = '@parameter.inner',
      --       ic = '@class.inner',
      --       ['if'] = '@function.inner',
      --     },
      --   },
      -- },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = '<c-space>',
          node_decremental = '<M-space>',
          node_incremental = '<c-space>',
          scope_incremental = '<c-s>',
        },
      },
      endwise = { enable = true },
      swap = { enable = true },
      highlight = { enable = true, additional_vim_regex_highlighting = { 'org' } },
      indent = { enable = true, disable = { 'ocaml', 'html' } },
    },
  },
  -- { 'nvim-treesitter/nvim-treesitter-textobjects' },
}
