return {
  {
    'nvim-treesitter/nvim-treesitter',
    config = function(opts)
      require('nvim-treesitter.configs').setup(opts.opts)
      local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
      parser_config.go_tags = {
        install_info = {
          url = 'https://github.com/DanWlker/tree-sitter-go_tags',
          files = { 'src/parser.c' },
          branch = 'main',
        },
      }
    end,
    opts = {
      auto_install = true,
      ensure_installed = {
        'lua',
        'luap',
        'luadoc',
        'vim',
        'vimdoc',
        'fennel',
        'requirements',
        'python',
        'pymanifest',
        'bash',
        'awk',
        'readline',
        'json',
        'json5',
        'jsonc',
        'jq',
        'yaml',
        'xml',
        'toml',
        'sql',
        'tsv',
        'markdown',
        'markdown_inline',
        'mermaid',
        'rst',
        'http',
        'html',
        'javascript',
        'typescript',
        'css',
        'jsdoc',
        'tsx',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'git_config',
        'git_rebase',
        'diff',
        'printf',
        'regex',
        'dockerfile',
        'llvm',
        'asm',
        'disassembly',
        'ini',
      },
      textobjects = {
        move = {
          enable = true,
          set_jumps = true,
          goto_next_end = { [']M'] = '@function.outer', [']['] = '@class.outer' },
          goto_next_start = { [']]'] = '@class.outer', [']m'] = '@function.outer' },
          goto_previous_end = { ['[M'] = '@function.outer', ['[]'] = '@class.outer' },
          goto_previous_start = { ['[['] = '@class.outer', ['[m'] = '@function.outer' },
        },
        select = {
          enable = true,
          lookahead = true,
          keymaps = {
            aa = '@parameter.outer',
            ac = '@class.outer',
            af = '@function.outer',
            ia = '@parameter.inner',
            ic = '@class.inner',
            ['if'] = '@function.inner',
          },
        },
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = '<c-space>',
          node_decremental = '<M-space>',
          node_incremental = '<c-space>',
          scope_incremental = '<c-s>',
        },
      },
      endwise = { enable = true },
      swap = { enable = true },
      highlight = { enable = true, additional_vim_regex_highlighting = { 'org' } },
      indent = { enable = true, disable = { 'ocaml', 'html' } },
    },
  },
  { 'nvim-treesitter/nvim-treesitter-textobjects' },
}
