local lspconfig = require("lspconfig")
local lsp_comf = vim.lsp.protocol.make_client_capabilities()
lsp_comf.textDocument.completion.completionItem.snippetSupport = true
local cmp_cap = require("cmp_nvim_lsp").default_capabilities(lsp_comf)

lspconfig.omnisharp.setup {
  capabilities = cmp_cap,
  on_attach = function(client, _)
    client.server_capabilities.semanticTokensProvider.legend = {
      tokenModifiers = { "static" },
      tokenTypes = {
        "comment",
        "excluded",
        "identifier",
        "keyword",
        "keyword",
        "number",
        "operator",
        "operator",
        "preprocessor",
        "string",
        "whitespace",
        "text",
        "static",
        "preprocessor",
        "punctuation",
        "string",
        "string",
        "class",
        "delegate",
        "enum",
        "interface",
        "module",
        "struct",
        "typeParameter",
        "field",
        "enumMember",
        "constant",
        "local",
        "parameter",
        "method",
        "method",
        "property",
        "event",
        "namespace",
        "label",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "xml",
        "regexp",
        "regexp",
        "regexp",
        "regexp",
        "regexp",
        "regexp",
        "regexp",
        "regexp",
        "regexp",
      },
    }
  end,
}
