local indent_width = 4
local stdpath = vim.fn.stdpath
local colourcolum_option = '88'
vim.opt.cmdheight = 0
vim.diagnostic.config { signs = false }
vim.opt.list = true
vim.opt.listchars = 'tab:  ,extends:·,precedes:·,nbsp:␣'
vim.g.mapleader = ' '
vim.g.maplocalleader = ';'
vim.opt.breakindent = true
vim.opt.termguicolors = true
vim.opt.laststatus = 3
vim.opt.showtabline = 0
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.ruler = false
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.numberwidth = 3
vim.opt.showmode = false
vim.opt.conceallevel = 2
vim.opt.updatetime = 300
vim.opt.colorcolumn = colourcolum_option
vim.opt.completeopt = { 'menu', 'menuone', 'noinsert', 'popup' }
vim.opt.virtualedit = 'block'
vim.opt.signcolumn = 'yes'
vim.opt.fillchars = 'eob: '
vim.opt.formatoptions = 'qjl1'
vim.opt.shortmess = vim.opt.shortmess + { c = true }
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.preserveindent = true
vim.opt.expandtab = true
vim.opt.shiftwidth = indent_width
vim.opt.softtabstop = indent_width
vim.opt.tabstop = indent_width
vim.opt.autowrite = true
vim.opt.mouse = ''
vim.opt.ignorecase = true
vim.opt.infercase = true
vim.opt.smartcase = true
vim.opt.fileencoding = 'utf-8'
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.undodir = stdpath 'data' .. '/undo'
vim.g.netrw_banner = 0
vim.g.netrw_liststyle = 3
vim.g.netrw_winsize = 20
vim.opt.pumheight = 10
vim.opt.pumwidth = 10
vim.opt.shortmess:append('WcC')
vim.opt.splitkeep = 'screen'
