return {
  {
    'nvim-treesitter/nvim-treesitter',
    config = function(opts)
      require('nvim-treesitter.configs').setup(opts.opts)
    end,
    opts = {
      auto_install = true,
      ensure_installed = {
        'lua',
        'luap',
        'luadoc',
        'vim',
        'vimdoc',
        'requirements',
        'python',
        'pymanifest',
        'bash',
        'awk',
        'readline',
        'json',
        'json5',
        'jsonc',
        'yaml',
        'xml',
        'toml',
        'sql',
        'tsv',
        'markdown',
        'markdown_inline',
        'http',
        'html',
        'javascript',
        'typescript',
        'css',
        'jsdoc',
        'tsx',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'git_config',
        'git_rebase',
        'diff',
        'printf',
        'regex',
        'dockerfile',
        'llvm',
        'asm',
        'disassembly',
        'ini',
      },
      textobjects = {
        move = {
          enable = true,
          set_jumps = true,
          goto_next_end = {
            [']M'] = '@function.outer',
            [']['] = '@class.outer',
          },
          goto_next_start = {
            [']]'] = '@class.outer',
            [']m'] = '@function.outer',
          },
          goto_previous_end = {
            ['[M'] = '@function.outer',
            ['[]'] = '@class.outer',
          },
          goto_previous_start = {
            ['[['] = '@class.outer',
            ['[m'] = '@function.outer',
          },
        },
        select = {
          enable = true,
          lookahead = true,
          keymaps = {
            aa = '@parameter.outer',
            ac = '@class.outer',
            af = '@function.outer',
            ia = '@parameter.inner',
            ic = '@class.inner',
            ['if'] = '@function.inner',
          },
        },
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = '<c-space>',
          node_decremental = '<M-space>',
          node_incremental = '<c-space>',
          scope_incremental = '<c-s>',
        },
      },
      highlight = { enable = true },
      indent = { enable = true, disable = { 'ocaml', 'html' } },
    },
  },
  { 'nvim-treesitter/nvim-treesitter-textobjects' },
}
